version: '3.7'

services:
  wireguard:
    restart: always
    image: whatwewant/wireguard:${SERVICE_WIREGUARD_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_WIREGUARD_DATA_PORT}:51820/udp
      - 127.0.0.1:${SERVICE_WIREGUARD_ADMIN_PORT}:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      WG_HOST: ${SERVICE_WIREGUARD_HOST}
      PASSWORD: ${SERVICE_WIREGUARD_PASSWORD}
      WG_DEFAULT_ADDRESS: ${SERVICE_WIREGUARD_DEFAULT_ADDRESS}

networks:
  default:
    external: true
    name: compose-ingress
