version: '3.7'

services:
  wireguard:
    restart: always
    image: whatwewant/wireguard:${SERVICE_WIREGUARD_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_WIREGUARD_DATA_PORT}:51820/udp
      - 0.0.0.0:${SERVICE_WIREGUARD_ADMIN_PORT}:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      # 会影响配置
      WG_HOST: ${SERVICE_WIREGUARD_HOST:-0.0.0.0}
      WG_PORT: ${SERVICE_WIREGUARD_DATA_PORT}
      PASSWORD: ${SERVICE_WIREGUARD_ADMIN_PASSWORD}
      #####
      # 自定义 DNS，无需变更
      WG_DEFAULT_DNS: ${SERVICE_WIREGUARD_DEFAULT_DNS:-1.1.1.1, 114.114.114.114}
      # 自定义网段，注意 WG_DEFAULT_ADDRESS 要和 WG_ALLOWED_IPS 一致
      #   比如：
      #     @example-1: WG_DEFAULT_ADDRESS = 10.8.0.x，则 WG_ALLOWED_IPS 为 10.8.0.0/16
      #     @example-2: WG_DEFAULT_ADDRESS = 10.10.0.x，则 WG_ALLOWED_IPS 为 10.10.0.0/16
      WG_DEFAULT_ADDRESS: ${SERVICE_WIREGUARD_DEFAULT_ADDRESS:-10.8.0.x}
      WG_ALLOWED_IPS: ${SERVICE_WIREGUARD_ALLOWED_IPS:-10.8.0.0/16}
      # Value in seconds to keep the "connection" open. If this value is 0, then connections won't be kept alive.
      WG_PERSISTENT_KEEPALIVE: ${SERVICE_WIREGUARD_PERSISTENT_KEEPALIVE:-25}
    volumes:
      # - /lib/modules:/lib/modules
      - ${SERVICE_DATA}:/etc/wireguard

networks:
  default:
    external: true
    name: compose-ingress
